version: "0.5"

is_strict: true

processes:
  flask:
   command: flask --app main run
   working_dir: ./app
   environment:
    - 'FLASK_APP=main'
    - 'FLASK_DEBUG=True'
   depends_on:
     db:
       condition: "process_healthy"
   availability:
    restart: "always"
    backoff_seconds: 5  # default: 1
    max_restarts: 0     # default: 0 (unlimited)

  db:
    command: >
      docker run -it --rm \
        --name ${CONTAINER_NAME} \
        -e POSTGRES_INITDB_ARGS="--locale-provider=icu --icu-locale=en_US.UTF-8" \
        -e POSTGRES_DB=${POSTGRES_DB} \
        -e POSTGRES_USER=${POSTGRES_USER} \
        -e POSTGRES_PASSWORD=${DB_PASS} \
        -p ${DB_PORT}:5432 \
        postgres:16.3-alpine3.20
    environment:
      - CONTAINER_NAME=${CONTAINER_NAME:-devbox-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS?}
      - DB_PORT=${DB_PORT:-5432}
    readiness_probe:
      exec:
        command: |
          timeout 30s bash -c "until docker exec ${CONTAINER_NAME} pg_isready; do sleep 3; done"
    is_tty: true
    shutdown:
      command: "docker stop ${CONTAINER_NAME}"
