version: "0.5"

is_strict: true

processes:
  flask:
   command: flask --app main run
   working_dir: ./app
   environment:
    - 'FLASK_APP=main'
    - 'FLASK_DEBUG=True'
  #  depends_on:
  #    db:
  #      condition: "process_started"
   availability:
    restart: "on_failure"
    backoff_seconds: 5    # default: 1
    # max_restarts: 10    # default: 0 (unlimited)

  # TODO: debug missing env vars
  # ! POSTGRES_PASSWORD
  db:
    command: >
      docker run -it --rm \
        --name "${DB_NAME?}" \
        -e POSTGRES_DB="${DB_NAME?}" \
        -e POSTGRES_USER="${DB_USER?}" \
        -e POSTGRES_PASSWORD="${DB_PASS:-postgres}" \
        -p "${DB_PORT:-5432}:5432" \
        postgres:16.3-alpine3.20
    environment:
      - 'DB_NAME=postgres'
      - 'DB_USER=postgres'
      - 'DB_PASS=postgres'
    is_tty: true
    shutdown:
      command: "docker stop devbox-postgres"
